name: Bug Report
description: Report any unusual behavior of FLRT-Resource at here.
title: "[Bug]<Name your bug title here> "
labels: ["bug"]
assignees:
  - JS_arthurliao  
  - HiltonLai
body:
  - type: markdown
    attributes:
      value: |
        **To help us with bug(s), please fill this form carefully!**
      
  - type: input
    id: version
    attributes:
      label: Q1. Resource Pack Version
      description: Please look at the file zip name and tell us the current resource psck version now you are using on!
      placeholder: v1.8.3
    validations:
      required: true
      
  - type: dropdown
    id: mod
    attributes:
      label: Q2. Catagory(Mod)
      description: Please hover and tell us which catagory does the bug related on! | You can also find it in "assets/" directory!
      multiple: true
      options:
        - car
        - eyemod
        - framedblocks
        - jsblock
        - minecraft
        - mlm
        - mtr
        - sodium
    validations:
      required: true

  - type: textarea
    id: issues
    attributes:
      label: Q3. List Issues
      description: Please list out issues you found within a list!
      value: |
        *
        *
        
  - type: textarea
    id: path
    attributes:
      label: Q4. Issue File(s) Path
      description: Please list out all the issue files path if possible!
      placeholder: |
        mtr:font/mtr.json
        mlm:sounds.json
        resourcepack/assets/mtr/font/mtr.json
        resourcepack/pack.mcmeta
    validations:
      required: false
      
  - type: textarea
    id: fix
    attributes:
      label: Q5. Fix The Issue File!
      description: If you know how to fix it? Then why not just tell us?!
      value: |
        **File1:** mtr:mtr_custom_resources.json
        ```json
        {}
        ``` 
        
        **File2:** ...
        ```json
        {}
        ```
        ...
    validations:
      required: false
        
  - type: checkboxes
    id: terms
    attributes:
      label: Q6. Before You Submit
      description: By submitting this issue report, you must agree with these below
      options:
        - label: I swear I'm not using this report form for spamming
          required: true
        - label: I had make sure my issue report is not existed
          required: true
        - label: Make sure to check everything before you submit
          required: true
        - label: I would like to provide my contact information on Q7. to get reply if there's any activity on my report
          required: false
          
  - type: input
    id: contact
    attributes:
      label: Q7. Contact
      description: If you chose the last option on the Q5., make sure you fill this question!
      placeholder: Your contact information here(make sure it's available)
    validations: 
      required: false
      
  - type: markdown
    attributes:
      value: |
        **Thanks for you taking time to complete this bug report, we hope this will make us even better.**
 
  - type: markdown
    attributes:
      value: |
        ### 𝐒𝐭𝐚𝐲 𝐜𝐨𝐧𝐧𝐞𝐜𝐭 𝐰𝐢𝐭𝐡 𝐅𝐋𝐑𝐓:
        [𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹 𝗪𝗲𝗯𝘀𝗶𝘁𝗲](https://www.mcflrt.net)
        [𝗗𝗶𝘀𝗰𝗼𝗿𝗱](https://discord.gg/vZGpr4WTBy)
        [𝗬𝗼𝘂𝗧𝘂𝗯𝗲](https://youtube.com/@hilton.l?si=8Wh8zk7wWvGU_tnf)
   
  - type: markdown
    attributes: 
      value: (c)<img src="FLRT_RC_500.png" width="20" height="20"/>Minecrafr FLRT Server, all rights reserved.
